[package]
name = "updatefiles"
version = "0.1.0"
authors = ["y-i"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"